### ISSUE TITLE
XmlHttpRequest to "http://grafanarel.s3.amazonaws.com/latest.json" fails

### ISSUE THREAD

**Issue by MoriTanosuke** [kamon-io/docker-grafana-graphite#11]
I'm using the container via https://registry.hub.docker.com/u/kamon/grafana_graphite/ and when I try to set up a new dashboard, I can not get metrics. My google chrome reports the following error in the developer console:

```
XMLHttpRequest cannot load http://grafanarel.s3.amazonaws.com/latest.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. (index):1
Failed to load resource: the server responded with a status of 404 (Not Found) 
```

When I try to open XXX I get this error

```
{"error":"IndexMissingException[[grafana-dash] missing]","status":404}
```

Editing the dashboard always hangs with this messages when trying to configure metrics:

```
Load metrics keys into elastic search
Work in progress...
```

Building the container myself using the latest Grafana does not fix the issue. Any ideas what I am missing?

**Comment by akauppi** [comment]
2 years old in 2 weeks :)
