### ISSUE TITLE
Update to grafana 1.9.0

### ISSUE THREAD

**Issue by justjoheinz** [kamon-io/docker-grafana-graphite#13]
The image still contains v1.7.0 with some patches. I have some issues with the grafana web ui, so maybe you could update to v1.9.0?

**Comment by ivantopo** [comment]
Long time has passed but I guess you might still be interested: the [grafana-upgrade-1.9.1](https://github.com/kamon-io/docker-grafana-graphite/tree/grafana-upgrade-1.9.1) branch contains a upgraded version of this docker image with a few enhancements, newer versions of both Graphite and Grafana and improved log configuration to avoid flooding the container with logs. 

Also, all patches have been removed, we are using vanilla versions of all components. The efforts required to maintain the patches seem not to pay for themselves, it was just about pretty printing metric names.

**Comment by ivantopo** [comment]
oh, and expect the changes to be merged to master and published right after our next Kamon release. :)

**Comment by outrunthewolf** [comment]
Great work man. Thanks for that! I ended up doing the same (re: patches). :+1:

**Comment by ivantopo** [comment]
the branch has been merged and the upgraded image is already available in the docker registry :).
