### ISSUE TITLE
Upgrade to Graphite 0.9.x

### ISSUE THREAD

**Issue by torkelo** [kamon-io/docker-grafana-graphite#14]
I would suggest using Graphite 0.9.x branch instead of 0.9.12 release. The 0.9.12 release and version tag of Graphite-web is missing the crucial maxDataPoints json api feature (https://github.com/graphite-project/graphite-web/pull/170)  This feature was implemented in March 2013 but not merged into 0.9.x branch until after the 0.9.12 version tag. 

Without this feature Grafana is really slow when viewing graphs for long time ranges due to the fact that Graphite will return a humongous number of datapoints when viewing time ranges above a couple of days (depending on lowest metric resolution).

**Comment by dpsoft** [comment]
@torkelo Thanks for pointing that, we just updated our Docker image to the Grafana 2.1.3 and and also we changed to the Graphite 0.9.x branch. BTW, congratulations and thanks for your awesome work with Grafana, definitely a great good to the community :).
