### ISSUE TITLE
Nginx conf override

### ISSUE THREAD

**Issue by outrunthewolf** [kamon-io/docker-grafana-graphite#15]
Think I can override the nginx config by mounting a local one to the correct path? I've tried but it hasn't quite worked.

I only ask because i'd like to basic auth the dashboard.

**Comment by ivantopo** [comment]
@outrunthewolf sorry, I didn't get to see this issue on time! Would you mind sharing if/how did you solve this issue?

**Comment by outrunthewolf** [comment]
I mounted a custom nginx config when the docker container is run.

    docker run -d -p 80:80 -p 8125:8125/udp -p 8126:8126 --name kamon-grafana-dashboard -v /etc/nginx/nginx.conf:/etc/nginx/nginx.conf -v /etc/nginx/.htpasswd:/etc/nginx/.htpasswd kamon/grafana_graphite

The only way I could get it working was to fork your repo and remove the "ADD" command on the dockerfile for the normal nginx config. I may have made a mistake, but from what I could tell I didn't seem to be able to overwrite the existing one.
