### ISSUE TITLE
installing grafana-upgrade-1.9 branch

### ISSUE THREAD

**Issue by behrad** [kamon-io/docker-grafana-graphite#19]
I did upgrade my docker to 1.5 on ubuntu 14.04.1 then

```
git clone -b grafana-upgrade-1.9.1 --single-branch https://github.com/kamon-io/docker-grafana-graphite.git
cd docker-grafana-graphite
sudo ./build
sudo ./start
```

however I see only a system-metrics appearing... no kamon dashboard... 
when I tried `http://localhost/#/dashboard/db/welcome` it says Dashboard Not Found!

`http://localhost/elasticsearch/grafana-dash/dashboard/welcome`
```
{
  "_index": "grafana-dash",
  "_type": "dashboard",
  "_id": "welcome",
  "found": false
}
```

**Comment by ivantopo** [comment]
Sorry, I forgot to push one last commit that actually loads the dashboards correctly. Also, please note that after the container is started, there is a delay of 20 seconds for the dashboards to appear. 

Please, pull the last commit and try to build and start again, regards!

**Comment by behrad** [comment]
So fast @ivantopo thank you :)
I felt that delay.... what is it for actually?

**Comment by ivantopo** [comment]
No problem! The thing about the delay is that for the dashboards to be searchable Grafan they need to be on ElasticSearch, so, there is a little [script] that post the dashboards to ElasticSearch after the container is up, the delay is just to make sure the ES is up before posting.. I was to lazy to code the retries in case of failure when I wrote that :D.

[script]: https://github.com/kamon-io/docker-grafana-graphite/blob/grafana-upgrade-1.9.1/grafana/dashboards/dashboard-loader.js

**Comment by behrad** [comment]
guessed it is the ES thing ;)
