### ISSUE TITLE
Instructions to run docker image  do not work on OSX

### ISSUE THREAD

**Issue by ShaneDelmore** [kamon-io/docker-grafana-graphite#21]
I am trying to follow the instructions to run the docker image from the Kamon.io site.

When I run the following command from the documentation:
docker run -d -v /etc/localtime:/etc/localtime:ro -p 80:80 -p 8125:8125/udp -p 8126:8126 --name kamon-grafana-dashboard kamon/grafana_graphite

I receive an error message:
Cannot start container 8143f54b606cd6bd9928ca05fdd47df3a05575ab396c290cc41a00dedede752a: setup mount namespace mounting /etc/localtime into /mnt/sda1/var/lib/docker/aufs/mnt/8143f54b606cd6bd9928ca05fdd47df3a05575ab396c290cc41a00dedede752a/etc/localtime not a directory

**Comment by ivantopo** [comment]
Shane, as pointed out in the [gitter chat], the `-v /etc/localtime:/etc/localtime:ro` is no longer necessary and it has been corrected on the post. We also pushed the very latest changes to the docker registry as mentioned in the chat, please pull the docker image again to ensure you are running the latest image.


[gitter chat]: https://gitter.im/kamon-io/Kamon?at=54e6f1ef48b72ed53095953b

**Comment by ShaneDelmore** [comment]
The new version works great, thanks!
