### ISSUE TITLE
Hostname auto-detection not implemented in Kamon Dashboard

### ISSUE THREAD

**Issue by ShaneDelmore** [kamon-io/docker-grafana-graphite#22]
Steps to reproduce:
Log into dashboard, by default see "hostname".
Switch to System Metrics, then see my computer name.

The workaround is to copy the computer name exactly as it is shown in the System Metrics dashboard and paste it in over "localhost" in the Kamon Dashboard.

**Comment by ivantopo** [comment]
I don't remember what commit actually fixed this, but the very latest published docker image with hash `169e15e33167` has the fix!
