### ISSUE TITLE
Document how to store data outside of container

### ISSUE THREAD

**Issue by coopernurse** [kamon-io/docker-grafana-graphite#26]
Thanks for putting together this image.  I may have missed it, but I didn't see any discussion of how to ensure that your data can survive container restarts.  This appears to work for me, but I may be missing some paths where data is stored:

```
docker run -v /data/graphite/whisper:/opt/graphite/storage/whisper -v /data/graphite/elasticsearch:/var/lib/elasticsearch -p 8000:80 -p 2003:2003 kamon/grafana_graphite
```

If you'd like I could fork and update the README, but I wanted to check to see if I'm doing this incorrectly first.

**Comment by ivantopo** [comment]
Hello James! The paths look correct so yes, that should be enough to ensure data persistence. If you opt for sending the PR I would suggest you to also put a small note on optionally mounting the logs folder in a volume as well, to simplify troubleshooting. Thanks!

**Comment by coopernurse** [comment]
Sounds good.  What log paths would you suggest documenting?  I see a few possibilities:

`/var/log/elasticsearch`
`/opt/graphite/storage/log`

Also, should users make the volumes they bridge to the container world-writeable?  I ended up doing that but I'm not sure if that's strictly required.

**Comment by coopernurse** [comment]
Oh, and another thing we did locally that we may want to document:  If you're using `collectd` to report stats, you need to expose `-p 2003:2003` for the graphite carbon port.  I can open a separate issue for that but since I'm already in the README I'm happy to do it as part of this issue.

**Comment by JakubKahovec** [comment]
I'm having difficulties with permissions when storing the elasticsearch data outside of the container (whisper data works fine). It only works when I set write permissions to group and other on the mapped volumed data but I don't think it's a correct solution.   Any ideas ?

**Comment by coopernurse** [comment]
Yeah I made the directories world-writeable as well.  It might work to chown the dir to the UID of elasticsearch. I didn't look at /etc/passwd in the container to see what UID that is though.

I've had similar issues with docker and external volumes.

**Comment by geoand** [comment]
+1 
Makes a lot of sense to have this configuration in the README

**Comment by joshrivers** [comment]
I think /opt/grafana/data should also be persisted, or you lose your dashboards.

**Comment by lahaxearnaud** [comment]
Yes you  need to add this to readme =) Thanks coopernurse

**Comment by joshrivers** [comment]
Created a pull request: https://github.com/kamon-io/docker-grafana-graphite/pull/60 which encapsulates the advise from this thread.

**Comment by mohdaliiqbal** [comment]
I have a question regarding the persistence of the data. I am trying to use data volume container however it does not seem to work with following commands - can someone tell me what is wrong in that

    docker create --name grafanadata \
      -v /opt/graphite/storage/whisper \
      -v /var/lib/elasticsearch \
      -v /opt/grafana/data \
      -v /opt/graphite/webapp
      -v /opt/graphite/storage/log \
      -v /var/log/elasticsearch \
      kamon/grafana_graphite /bin/true

    docker run \
      --detach \
      --volume-from grafanadata \
       --publish=80:80 \
       --publish=81:81 \
       --publish=8125:8125/udp \
       --publish=8126:8126 \
       --name grafana-dashboard \
       kamon/grafana_graphite

**Comment by joshrivers** [comment]
@mohdaliiqbal It should be

     --volumes-from

Plural. :)

**Comment by mohdaliiqbal** [comment]
FML!

**Comment by rholloway** [comment]
I think /src/dashboards also needs to be persisted or at least documented better in README as I've lost configured dashboards because of it twice :/ Looking at the Dockerfile and scripts, there is a dashboard-loader tool that runs under supervisor which imports dashboard JSON files from that directory and basically overwrites anything that existed. In my case, I had reconfigured the system metrics dashboard and on container launch all changes get overwritten.

**Comment by akauppi** [comment]
Lots of done work here - maybe the issue can be closed?

@rholloway 's issue is probably a completely separate one
