### ISSUE TITLE
Network blackhole

### ISSUE THREAD

**Issue by sfthomas** [kamon-io/docker-grafana-graphite#30]
The start script uses 'docker kill' - which is quite fast and untidy at the same time.
I was forwarding additional stats to this container via statsd, and it took me a few days to figure out why the clients stop sending data after I restart this container.

'docker kill' will cause the bound ports not to be closed properly, and that might (and have) cause the restart go unnoticed by the clients, which will continue to send data that ends up being discarded.
Switching to 'docker stop' solves the issue.

**Comment by behrad** [comment]
:+1:

**Comment by akauppi** [comment]
The code now uses `docker-compose` and there is no `docker kill` anywhere. Can this be closed?
