### ISSUE TITLE
Update plan to grafana 2.x ?

### ISSUE THREAD

**Issue by behrad** [kamon-io/docker-grafana-graphite#32]
Hi @ivantopo ,
Hope you are at your best these days... Any plan to upgrade grafana dashboard to latest?

**Comment by ivantopo** [comment]
Well, we certainly thought about it and there is an open PR that makes the upgrade but I didn't have the bandwidth to get into that now.. We will, at some point, for sure! but I don't know when :S... Still, you can look at #29 and try it out!

**Comment by dpsoft** [comment]
Done https://github.com/kamon-io/docker-grafana-graphite/pull/29
