### ISSUE TITLE
Unable to see the stats beyond 7 days

### ISSUE THREAD

**Issue by thusharaPaul** [kamon-io/docker-grafana-graphite#33]
I have the latest docker installed and running for more than a month now but i am not able to see the graphs beyond 7 days. Is it normal or do i need to change something in config files to see graphs for more days?

**Comment by ivantopo** [comment]
Hello Thushara,

certainly it is expected that you will only see data for the last 7 days, as the container is configured to keep just that. In case you want to change that configuration please take a look at this file: https://github.com/kamon-io/docker-grafana-graphite/blob/master/graphite/storage-schemas.conf#L3

**Comment by lachesis** [comment]
What's the best way to persist settings across container runs? Should I move my conf directory to a volume?

**Comment by ksingh7** [comment]
@thusharaPaul @lachesis  did you managed to fix this problem ? 
I have similar problem #79
