### ISSUE TITLE
Grafana 2 Usage

### ISSUE THREAD

**Issue by behrad** [kamon-io/docker-grafana-graphite#43]
I built an image from the latest master branch, and started the container, however I'm pretty newbie to the new structure and grafana 2.x
I didn't see queries and metrics to build my own panels, Should I define graphite as a Datasource in grafana? If yes, then shouldn't we open graphite's port also?

**Comment by behrad** [comment]
solved via adding a Graphite dataSource via http://localhost:8000 with proxy option

**Comment by ivantopo** [comment]
Nice that you figured it out! This actually happened to me as well a few days ago and I didn't notice that the README states that the datasource needs to be created. I would like to explore if there is a way to have it automatically set up, though. Let's see!
