### ISSUE TITLE
[PROPOSAL] Upgrade grafana to 2.6.*

### ISSUE THREAD

**Issue by lahaxearnaud** [kamon-io/docker-grafana-graphite#67]
Hello,

Is-it possible to upgrade grafana to v2.6.\* in order to have table panels in dashboard.

Thanks,

Arnaud

**Comment by fancellu** [comment]
Or even the latest beta 3?

**Comment by jarek-przygodzki** [comment]
There's a pull request  with upgrade to 3.0.4 - #76. If it's not merged and published to Docker Hub in timely manner I will probably push my fork.

**Comment by akauppi** [comment]
#76 is merged and current `master` uses `grafana-3.1.1-1470047149`. This issues should be closed.

**Comment by dpsoft** [comment]
@akauppi thanks!!
