### ISSUE TITLE
From Cassandra: "Unable to report to Graphite" "Connection refused", UDP vs. TCP ?

### ISSUE THREAD

**Issue by laugimethods** [kamon-io/docker-grafana-graphite#69]
Hi,

I'm able to send metrics from Kamon to Graphite with success, but not from Cassandra 
(`cassandra -f  -Dcassandra.metricsReporterConfigFile=metrics-reporter-config-graphite.yaml`):
```
WARN  14:15:05 Unable to report to Graphite
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_60]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_60]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_60]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_60]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_60]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_60]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_60]
	at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_60]
	at java.net.Socket.<init>(Socket.java:244) ~[na:1.8.0_60]
```

I'm following those instructions: [Pluggable metrics reporting in Cassandra](http://www.datastax.com/dev/blog/pluggable-metrics-reporting-in-cassandra-2-0-2)

Versions used:
- Cassandra: 2.2.5
- metrics-graphite (deployed in cassandra/lib): [metrics-graphite-3.1.2.jar](http://central.maven.org/maven2/io/dropwizard/metrics/metrics-graphite/3.1.2/metrics-graphite-3.1.2.jar)
- docker-grafana-graphite: master branch, at date March 17, 2016

Configuration of the `metrics-reporter-config-graphite.yaml` file:
```
graphite:
  -
    period: 60
    timeunit: 'SECONDS'
    hosts:
     - host: '192.168.99.100'
       port: 8125

```

What I did notice (using Wireshark) is that the protocol used by Kamon is UDP, the configuration of the 8125 port opened by Docker is also UDP while Cassandra is sending TCP packets...

Any help?
Thanks in advance.

**Comment by laugimethods** [comment]
There is no exception raised when the configured port is 8126 (which is defined as TCP), but no Cassandra metrics either are available in Graphite...

**Comment by laugimethods** [comment]
I tried to add TCP capabilities to docker-grafana-graphite by modifying 'statsd/config.js':
```
  servers:
	[ 
	  { server: "./servers/tcp", port: 8123, mgmt_port: 8124 },
	  { server: "./servers/udp", port: 8125, mgmt_port: 8126 },
	]

```
and by exposing those ports through 'Dockerfile':
```
# StatsD TCP port
EXPOSE  8123

# StatsD TCP Management port
EXPOSE  8124
```

but without success...

**Comment by ivantopo** [comment]
hello @laugimethods, the problem here is that Kamon talks to this image using the StatsD protocol via UDP, which later dumps the data to the internal Graphite process, but that process it not being exposed. 

As you can see here: https://github.com/kamon-io/docker-grafana-graphite/blob/master/graphite/carbon.conf#L31, the Graphite listening bits are in port 2003, which is not being exposed by default, try exposing that port and pointing your Cassandra there, that should make it work.

**Comment by laugimethods** [comment]
Works great!
Thank you very much.
