### ISSUE TITLE
apt-get error running ./build

### ISSUE THREAD

**Issue by glidester** [kamon-io/docker-grafana-graphite#72]
There is an error when attempting to build the master branch:

`Sending build context to Docker daemon 285.7 kB
Step 1 : FROM ubuntu:14.04
 ---> 90d5884b1ee0
Step 2 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> ef4d39442d50
Step 3 : RUN apt-get -y install software-properties-common
 ---> Running in 39724b803a54
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package software-properties-common
The command '/bin/sh -c apt-get -y install software-properties-common' returned a non-zero code: 100`

It is caused by this line in the Dockerfile:
`apt-get -y install software-properties-common`
being called before: 
`apt-get -y update`

I'd make a pull request but its such a trivial fix I imagine it would be easier for someone more involved in the project to edit it.

Cheers

**Comment by akauppi** [comment]
I'm seeing this fixed, but it's a bit weird to have two `apt-get -y install`s. Would you have a look and close this issue if everything looks okay?

```
# Install all prerequisites
RUN     apt-get -y update
RUN     apt-get -y install software-properties-common
RUN     add-apt-repository -y ppa:chris-lea/node.js
RUN     apt-get -y update
RUN     apt-get -y install python-django-tagging python-simplejson python-memcache python-ldap python-cairo python-pysqlite2 python-support \
                           python-pip gunicorn supervisor nginx-light nodejs git wget curl openjdk-7-jre build-essential python-dev
```
