### ISSUE TITLE
Example image is for a dashbaord that isn't even provided any more

### ISSUE THREAD

**Issue by Sushisource** [kamon-io/docker-grafana-graphite#82]
It seems this repo is pretty dead, because it's got some fairly serious issues that prevent it from being usable.

Namely, this big pretty example dashboard you show in the readme isn't even in the current version of the repository. You get nothing when you start this up for the first time. In fact, as some of the other issues mention, it's not even clear to me if my data is making it into graphite, but maybe that's my issue.

Also, unrelated, I had to run docker compose with the priviledged option to even get the web UI to render at all.

**Comment by akauppi** [comment]
I got the same problem as @Sushisource 

While the repo looks *splendid* to me, it falls short at this point. I'm using macOS and would like to help get these things fixed.

**Comment by dpsoft** [comment]
@Sushisource @akauppi I've restore the deleted dashboards..please let me know if all is ok.
