### ISSUE TITLE
Noob question: Storing metrics outside a container

### ISSUE THREAD

**Issue by kotter** [kamon-io/docker-grafana-graphite#9]
Hello- I'm relatively new to Graphite/Carbon and Docker, and was trying to figure out via the configuration files...

Where do I configure the destination file system for storing collected metrics?  If I had SAN space mounted outside the container, where do I account for piping the metrics off that that mount?

I apologize for the simplicity of this, I just have yet to find anything documented how to keep data resident outside of the Docker container.

Thanks!

**Comment by sgunturi** [comment]
FYI to anybody looking to do this - the directory is now `/opt/graphite/storage/whisper`.

**Comment by ivantopo** [comment]
@sgunturi thanks for pointing that out!
